import { useCallback, useEffect, useState } from "react";
import { api, type GameDashboard, type GameInfo } from "../lib/api";

const STATUS: Record<string, string> = { draft: "Bản nháp", lobby: "Lobby", active: "Đang live", closed: "Đã kết thúc" };

export function GameManagementPage({ gameId, onLobby, onEdit, onBack }: { gameId: string; onLobby: () => void | Promise<void>; onEdit: () => void; onBack: () => void }) {
  const [game, setGame] = useState<GameInfo | null>(null);
  const [dashboard, setDashboard] = useState<GameDashboard | null>(null);
  const [live, setLive] = useState<{ participantCount: number; votedCount: number; waitingCount: number; optionCounts: Record<string, number> } | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    try {
      const [g, d] = await Promise.all([api.getGame(gameId), api.getGameDashboard(gameId)]);
      setGame(g.game); setDashboard(d); setError("");
      if (g.game.status === "active") api.getGameLiveStats(gameId).then(setLive).catch(() => {});
    } catch (e: any) { setError(e?.message ?? "Không thể tải dashboard."); }
  }, [gameId]);
  useEffect(() => { void load(); const t = setInterval(() => void load(), 3000); return () => clearInterval(t); }, [load]);

  if (!game || !dashboard) return <div className="grid min-h-screen place-items-center bg-stage-950 text-white"><p>Đang tải dashboard…</p></div>;
  const canEdit = game.status === "draft" || (game.status === "lobby" && dashboard.participantCount === 0);
  const totalVotes = dashboard.totalVotes + (live && game.status === "active" ? live.votedCount : 0);

  return <div className="min-h-screen bg-stage-950 text-white"><header className="sticky top-0 z-20 border-b border-white/10 bg-stage-950/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><button onClick={onBack} className="text-sm font-bold text-white/45">← My Games</button><div className="flex gap-2">{canEdit && <button onClick={onEdit} className="rounded-xl bg-white/8 px-4 py-2.5 text-sm font-bold">Chỉnh sửa</button>}<button onClick={async()=>{setBusy(true);try{await onLobby()}catch(e:any){setError(e?.message??"Không thể mở Lobby.")}finally{setBusy(false)}}} disabled={busy || !game.questions?.length || game.status === "active"} className="rounded-xl bg-amber px-4 py-2.5 text-sm font-black text-stage-950 disabled:opacity-40">{busy ? "Đang mở…" : game.status === "closed" ? "Mở lại Lobby →" : "Mở Lobby →"}</button></div></div></header>
  <main className="mx-auto max-w-7xl px-5 py-7 md:px-8 md:py-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.22em] text-amber">GAME DASHBOARD</p><h1 className="mt-2 font-display text-3xl font-black md:text-5xl">{game.title}</h1><p className="mt-2 text-sm text-white/40">PIN {game.pin} · {STATUS[game.status] ?? game.status}</p></div><button onClick={()=>void load()} className="rounded-xl bg-white/6 px-4 py-2 text-xs font-bold text-white/55">↻ Làm mới</button></div>
  {error && <div className="mt-5 rounded-2xl border border-coral/30 bg-coral/10 p-4 text-sm text-coral">{error}</div>}
  <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Người tham gia" value={dashboard.participantCount} /><Metric label="Tổng lượt vote" value={totalVotes} /><Metric label="Số câu hỏi" value={dashboard.questions.length} /><Metric label="Trạng thái" value={STATUS[game.status] ?? game.status} text /></section>
  {game.status === "active" && live && <section className="mt-5 grid gap-4 sm:grid-cols-3"><Metric label="Đã vote câu hiện tại" value={live.votedCount} /><Metric label="Đang chờ" value={live.waitingCount} /><Metric label="Tổng người online" value={live.participantCount} /></section>}
  <section className="mt-7"><div className="mb-4"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-white/35">RANKING BY QUESTION</p><h2 className="mt-2 font-display text-2xl font-black">Bảng xếp hạng từng câu</h2></div><div className="grid gap-5 lg:grid-cols-2">{dashboard.questions.map(q=><VerticalChart key={q.questionId} q={q} />)}</div></section>
  <section className="mt-7 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-[28px] border border-white/10 bg-stage-900 p-5 md:p-7"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-white/35">VOTE HISTORY</p><h2 className="mt-2 font-display text-2xl font-black">Lịch sử vote</h2><p className="mt-1 text-xs text-white/30">Chỉ hiển thị lựa chọn và timestamp, không hiển thị danh tính.</p><div className="mt-5 max-h-[420px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-stage-900 text-[11px] uppercase tracking-wider text-white/35"><tr><th className="px-3 py-3">Timestamp</th><th className="px-3 py-3">Câu</th><th className="px-3 py-3">Lựa chọn</th></tr></thead><tbody>{[...dashboard.voteHistory].reverse().map((r,i)=><tr key={`${r.timestamp}-${i}`} className="border-t border-white/5"><td className="px-3 py-3 font-mono text-xs text-white/55">{new Date(r.timestamp).toLocaleString("vi-VN")}</td><td className="px-3 py-3 font-bold">Q{r.questionNumber}</td><td className="px-3 py-3 text-white/70">{r.optionLabel}</td></tr>)}</tbody></table>{dashboard.voteHistory.length===0&&<p className="py-12 text-center text-white/30">Chưa có vote đã chốt.</p>}</div></div>
  <div className="rounded-[28px] border border-white/10 bg-stage-900 p-5 md:p-7"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-white/35">PARTICIPANTS</p><h2 className="mt-2 font-display text-2xl font-black">Người tham gia</h2><div className="mt-6 grid place-items-center rounded-3xl bg-white/[.04] py-10"><div className="font-display text-6xl font-black text-amber">{dashboard.participantCount}</div><p className="mt-2 text-sm text-white/40">người đã tham gia Game</p></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-white/30">Mốc tham gia gần nhất</p><div className="mt-3 space-y-2">{dashboard.participantJoinTimestamps.slice(-8).reverse().map((t,i)=><div key={`${t}-${i}`} className="flex justify-between rounded-xl bg-white/[.04] px-3 py-2 text-xs"><span className="text-white/40">Người tham gia #{dashboard.participantJoinTimestamps.length-i}</span><span className="font-mono text-white/55">{new Date(t).toLocaleString("vi-VN")}</span></div>)}</div></div></section>
  </main></div>;
}

function Metric({label,value,text=false}:{label:string;value:number|string;text?:boolean}){return <div className="rounded-[22px] border border-white/10 bg-stage-900 p-5"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-white/35">{label}</p><p className={`mt-3 font-display font-black ${text?"text-xl":"text-4xl"}`}>{value}</p></div>}
function VerticalChart({q}:{q:GameDashboard["questions"][number]}){const max=Math.max(1,...q.ranking.map(x=>x.votes));return <article className="rounded-[28px] border border-white/10 bg-stage-900 p-5"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-amber">CÂU {q.questionNumber}</p><h3 className="mt-2 line-clamp-2 min-h-12 font-display text-lg font-black">{q.question}</h3><div className="mt-6 flex h-64 items-end gap-3 border-b border-white/10 px-2">{q.ranking.map((x,i)=><div key={x.optionId} className="flex h-full min-w-0 flex-1 max-w-24 flex-col items-center justify-end"><b className="mb-2 text-sm">{x.votes}</b><div className="w-full rounded-t-xl bg-amber" style={{height:`${Math.max(6,x.votes/max*82)}%`}}/><span className="mt-3 w-full truncate text-center text-xs font-bold text-white/55">{String.fromCharCode(65+i)} · {x.label}</span></div>)}</div><div className="mt-4 flex justify-between text-xs text-white/35"><span>{q.totalVotes} vote</span><span>{q.noAnswerCount} không chọn</span></div></article>}
