import { useCallback, useEffect, useState } from "react";
import { api, type GameInfo } from "../lib/api";

export function GameManagementPage({ gameId, onLobby, onEdit, onBack }: { gameId: string; onLobby: () => void; onEdit: () => void; onBack: () => void }) {
  const [game, setGame] = useState<GameInfo | null>(null);
  const [busy, setBusy] = useState(false);
  const load = useCallback(() => api.getGame(gameId).then(r => setGame(r.game)), [gameId]);
  useEffect(() => { void load(); }, [load]);
  if (!game) return <div className="grid min-h-screen place-items-center bg-stage-950 text-white">Đang tải Game…</div>;
  const action = async () => { setBusy(true); try { await api.enterGameLobby(game.id); onLobby(); } finally { setBusy(false); } };
  return <div className="min-h-screen bg-stage-950 text-white"><header className="border-b border-white/10 bg-stage-950/90"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><button onClick={onBack} className="text-sm font-bold text-white/45">← My Games</button><div className="flex gap-2"><button onClick={onEdit} className="rounded-xl bg-white/8 px-4 py-2.5 text-sm font-bold">Chỉnh sửa</button><button onClick={() => void action()} disabled={busy || game.questions?.length === 0} className="rounded-xl bg-amber px-4 py-2.5 text-sm font-black text-stage-950 disabled:opacity-40">{busy ? "Đang mở…" : "Mở Lobby →"}</button></div></div></header><main className="mx-auto max-w-6xl px-5 py-8"><div className="grid gap-5 md:grid-cols-[1.5fr_1fr]"><section className="overflow-hidden rounded-[32px] border border-white/10 bg-stage-900"><div className="h-48 bg-gradient-to-br from-stage-800 to-stage-700">{game.cover_url && <img src={game.cover_url} alt="" className="h-full w-full object-cover" />}</div><div className="p-6 md:p-8"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-amber">GAME</p><h1 className="mt-2 font-display text-3xl font-black md:text-4xl">{game.title}</h1><div className="mt-5 inline-flex items-center gap-3 rounded-2xl bg-black/20 px-5 py-3"><span className="text-xs font-bold text-white/35">PIN</span><span className="font-mono text-2xl font-black tracking-[.18em] text-amber">{game.pin}</span></div></div></section><section className="rounded-[32px] border border-white/10 bg-stage-900 p-6 md:p-8"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-white/35">QUESTIONS</p><div className="mt-5 space-y-3">{game.questions?.map((q,i)=><div key={q.id} className="flex gap-3 rounded-2xl bg-white/5 p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-amber text-xs font-black text-stage-950">{i+1}</span><div className="min-w-0"><p className="font-display font-bold">{q.question}</p><p className="mt-1 text-xs text-white/35">{q.options?.length ?? 0} đáp án · {q.duration_seconds}s</p></div></div>)}</div></section></div></main></div>;
}
